pandas training with jeson brownlee

In [1]:
import numpy as np
import pandas as pd

In [2]:
my_array = np.array([1,2,3])

In [3]:
row_names = ['a','b','c']

In [5]:
my_series = pd.Series(my_array, index = row_names)

In [41]:
print(my_series)

a    1
b    2
c    3
dtype: int64

In [42]:
print(my_series[0])

1

C:\Users\4-063-p-jomboze\AppData\Local\Temp\ipykernel_6468\739979572.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(my_series[0])

In [43]:
print(my_series[1])

2

C:\Users\4-063-p-jomboze\AppData\Local\Temp\ipykernel_6468\2700731362.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(my_series[1])

In [44]:
print(my_series.iloc[2])

3

In [11]:
print(my_series.loc['a'])

1

In [15]:
#make a dataframe

In [39]:
import numpy as np
import pandas as nd
myarray = np.array([
          [1,2,3],
          [4,5,6]
])
rownames = ['a' , 'b']
colnames = ['one','two','tree']
df = pd.DataFrame(myarray, index=rownames, columns = colnames)
df

   one  two  tree
a    1    2     3
b    4    5     6

In [49]:
myarray = np.array([
          [13,145,45],
          [40,158,60],
          [29,175,95],
          [35,186,79]
    
])
rownames = ['ali' , 'bahram', 'saeed', 'mehdi']
colnames = ['age','height', 'weight']
new_df = pd.DataFrame(myarray, index=rownames, columns = colnames)
new_df

        age  height  weight
ali      13     145      45
bahram   40     158      60
saeed    29     175      95
mehdi    35     186      79